include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors_in_immutables: ignore
    unnecessary_string_interpolations: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
