name: weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  provider: ^6.0.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  lottie: ^3.3.1
  flex_color_scheme: ^8.2.0
  easy_localization: ^3.0.7+1
  flutter_local_notifications: ^19.2.1
  flutter_svg: ^2.2.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/
    - assets/img/
    - assets/lang/
    - assets/svg/
